import MainLayout from "@/layout/MainLayout";
import Planner from "@/sections/planner";
import { useTheme } from "@emotion/react";
import Head from "next/head";

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero /> */}
      <MainLayout>
        <Planner />
        {/* <Map /> */}
      </MainLayout>
    </>
  );
}
