import Illustration from "@/components/Illustration";
import MainLayout from "@/layout/MainLayout";
import HeaderTravelInput from "@/sections/planner";
import Hero from "@/sections/hero";
import Map from "@/sections/map/Map";
import { useTheme } from "@emotion/react";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero /> */}
      <MainLayout>
        <HeaderTravelInput />
      </MainLayout>
      <main>{/* <Map /> */}</main>
    </>
  );
}
